repositories:
  remote:
   - https://stocksoftware.jfrog.io/stocksoftware/maven2
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.14

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1

  getopt4j: org.realityforge.getopt4j:getopt4j:jar:1.3

  jsonb_api: javax.json.bind:javax.json.bind-api:jar:1.0
  yasson: org.eclipse:yasson:jar:1.0
  javax_json: org.glassfish:javax.json:jar:1.1

  jsoup: org.jsoup:jsoup:jar:1.13.1

  gir: org.realityforge.gir:gir-core:jar:0.11
